In [1]:
print("hello")

hello


In [2]:
import numpy as np
from sklearn.model_selection import StratifiedKFold, GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.metrics import roc_auc_score, make_scorer
import os
from sklearn import metrics
import seaborn as seabornInstance 

from sklearn.linear_model import LinearRegression
import pandas as pd
from fancyimpute import KNN
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency
from random import randrange, uniform

Using TensorFlow backend.


In [3]:
sample_matrix = np.matrix('123;456')

In [4]:
sample_matrix

matrix([[123],
        [456]])

In [5]:
sample_matrix *2
sample_matrix/3

matrix([[ 41.],
        [152.]])

In [6]:
# now we will work with dataframe
df = pd.DataFrame({'age':[1,2,3],
                  'gender':["male","female","M"],
                   'Income':[12,23,34]
                   
                  })

In [7]:
df

age  gender  Income
0    1    male      12
1    2  female      23
2    3       M      34

In [8]:
df.rename(columns = {'gender':'gender_vi',
                     'Income':'Income_vi'})

age gender_vi  Income_vi
0    1      male         12
1    2    female         23
2    3         M         34

In [9]:
from ggplot import mtcars
df_mtcars = mtcars

ModuleNotFoundError: No module named 'ggplot'

In [ ]:
from ggplot import mtcars

In [ ]:
german = pd.read_csv("German.csv")
germ

In [11]:
os.chdir('/Users/chandan/desktop/eduWork_project/')

In [ ]:
german['newcol'] = 0

In [ ]:
german['newcol'] = german['Duration'] + german['Amount']

In [ ]:
os.chdir("/Users/chandan/desktop/eduWork_project/")

In [ ]:
for i in range(len(german)):
    german['newcol'].loc[i] = german['Amount'].loc[i] + german['Duration'].loc[i]    

In [ ]:
tips

In [ ]:
sns.pairplot(data)

In [ ]:
sns.pairplot(data, hue = 'target')

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [12]:
data = pd.read_csv("train.csv")

In [ ]:
data

In [ ]:
data.shape
data.describe()


In [ ]:
data_vis = data.head(100000)
data_vis

In [ ]:
plt.figure(figsize=(500,100))
sns.heatmap(data_vis.corr(),annot = True)
plt.show()

In [ ]:
sns.heatmap?

In [ ]:
data_vis2 = data.tail(100000)
data_vis2

In [ ]:
plt.figure(figsize=(500,100))
sns.heatmap(data_vis2.corr(),annot = True)
plt.show()

In [ ]:
data.corr()

In [ ]:
data.corr()
corr = data[:50].corr()
sns.heatmap(corr,
           xticketlabels = corr.columns,
           yticketlabels = corr.columns)


In [ ]:
#missing value present there would be
missing_val = pd.DataFrame(data.isnull().sum())
missing_val = missing_val.rename(columns = {'index': 'Variables', 0: 'Missing_percentage'})

#Calculate percentage
missing_val['Missing_percentage'] = (missing_val['Missing_percentage']/len(data))*100

#descending order
missing_val = missing_val.sort_values('Missing_percentage', ascending = False).reset_index(drop = True)

#save output results 
missing_val.to_csv("Miising_perc.csv", index = False)

In [ ]:
data['var_0'].loc[70] = np.nan

In [ ]:
data["target"].hist()
sns.pairplot(data, hue = 'target',height = 3, aspect = 1)

pd.plotting.scatter_matrix(data,flagsize = (12,10))
plt.show()

In [ ]:
sns.heatmap(corr, 
        xticklabels=corr.columns,
        yticklabels=corr.columns)

In [ ]:
#imputation method
#mean = 10.67991236556198
#median = 10.5247
#actual value = 8.5576
#knn = 

In [ ]:
data["var_0"] = data["var_0"].fillna(data["var_0"].median())

In [ ]:
data["var_0"].loc[70]

In [ ]:
lis = []
for i in range(0, data.shape[1]):
    #print(i)
    if(data.iloc[:,i].dtypes == 'object'):
        data.iloc[:,i] = pd.Categorical(data.iloc[:,i])
        #print(marketing_train[[i]])
        data.iloc[:,i] = data.iloc[:,i].cat.codes 
        data.iloc[:,i] = data.iloc[:,i].astype('object')
        
        lis.append(data.columns[i])
    

In [ ]:
for i in range(0, data.shape[1]):
    data.iloc[:,i] = data.iloc[:,i].replace(-1, np.nan) 

In [ ]:
data = pd.DataFrame(KNN(k = 3).fit_transform(data), columns = data.columns)


In [ ]:
#data visualization
data['var_0'].hist()
data['var_1'].hist()

In [ ]:
sns.countplot(x ='target',data = data)


In [ ]:
#corr = data.corr() # df is the pandas dataframe
value = data[data.columns[1:]].corr()['target'][:]

value.sort_values(ascending = False)

In [13]:

#Linear rregression
from sklearn import tree
from sklearn.model_selection import train_test_split

X = [data['var_6'],data['var_110'],data['var_53'],data['var_26']]

y = data['target']

X = np.asarray(X).transpose()

X_train, X_test, y_train, y_test = train_test_split(
    
    X, y, test_size=0.33, random_state=42)
#X_train = [data['var_6'],data['var_110'],data['var_53'],data['var_26']]
#Y_train = data['target']
#split
#X_train = np.asarray(X).transpose()
#Y
model = tree.DecisionTreeClassifier()

In [14]:
print(X_train)
print(y_train)

[[  4.8381   4.2416   6.6757  -7.7491]
 [  5.5449   7.3248   6.1623  -9.0584]
 [  4.901    3.9419   5.8249 -11.6446]
 ...
 [  5.2315  10.2464   6.2957  -3.9577]
 [  3.1534   5.8074   7.0765  -5.5393]
 [  4.2625   3.2183   5.2121  -7.2985]]
39290     0
105995    0
2423      0
64689     0
158534    1
         ..
119879    0
103694    0
131932    0
146867    0
121958    0
Name: target, Length: 134000, dtype: int64


In [ ]:
model = model.fit(X_train,y_train)


In [ ]:
#dv = pd.read_csv("test.csv")
#dv

In [ ]:
y_pred = model.predict(X_test)
y_correct_pred = y_pred-y_test
y_correct_pred = np.asarray(y_correct_pred)
failed_pred = np.count_nonzero(y_correct_pred)
acc = 100-failed_pred/len(y_correct_pred)*100
print(acc)

In [ ]:
#Random forest
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
# Fit on training data


In [ ]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred.transpose()

In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
#SVM classification
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred_svm = clf.predict(X_test)

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_svm))

In [ ]:
sns.pairplot(data1,height = 5);
plt.show()

In [ ]:
list_data  = list(data1)
dataframe_now = pd.DataFrame(data1)
#sns.pairplot(list_data);
#plt.show()

In [ ]:
sns.pairplot(dataframe_now['target'],dataframe_now, size = 5);
plt.show()

In [ ]:
for i in lis:
    data.loc[:,i] = data.loc[:,i].round()
    data.loc[:,i] = data.loc[:,i].astype('object')

In [ ]:
 df.copy() = data

In [ ]:
data.columns
data_list = list(data)

In [ ]:
%matplotlib inline  
plt.boxplot(data)
#cnames =  ["var_0", "var_1", "var_3", "var_4", "var_5", "var_6", "var_7", "var_190",
#           "var_193", "var_195", "var_8"]
cnames = data_list 
cnames = data 
for i in cnames:
    print(i)
    q75, q25 = np.percentile(data.loc[:,i], [5 ,10])
    iqr = q75 - q25

    min = q25 - (iqr*1.5)
    max = q75 + (iqr*1.5)
    print(min)
    print(max)
    
    data = data.drop(data[data.loc[:,i] < min].index)
    data = data.drop(data[data.loc[:,i] > max].index)
    

In [ ]:
Extract quartiles
 q75, q25 = np.percentile(data['var_0'], [8 ,25])

 #Calculate IQR
 iqr = q75 - q25

 #Calculate inner and outer fence
 minimum = q25 - (iqr*1.5)
 maximum = q75 + (iqr*1.5)

# #Replace with NA
 data.loc[data['var_0'] < minimum,:'var_0'] = np.nan
 data.loc[data['var_0'] > maximum,:'var_0'] = np.nan

# #Calculate missing value
 missing_val = pd.DataFrame(data.isnull().sum())

# #Impute with KNN
 data = pd.DataFrame(KNN(k = 3).complete(data), columns = data.columns)

In [ ]:
corr=data.iloc[:,:198].corr()
fig, ax=plt.subplots(figsize=(80,80))
# Generate a custom diverging colormap
Cmap=sns.diverging_palette(220,100,as_cmap=True)

# Draw the heatmap
_= sns.heatmap(corr,  ax=ax, annot=True,   vmin=-1, linewidths=0.2)

In [ ]:
plt.figure(figsize = (198,100))
sns.heatmap(data.corr(), annot = True)
plt.show()


In [ ]:
sns.heatmap(corr, 
        xticklabels=corr.columns,
        yticklabels=corr.columns)

In [ ]:
cat_names = ["var_0", "var_1", "var_3", "var_4", "var_5", "var_6", "var_7", "var_190",
           "var_193", "var_195", "var_8"]

In [ ]:
for i in cat_names:
    print(i)
    chi2, p, dof, ex = chi2_contingency(pd.crosstab(data['target'],data[i]))
    print(p)

In [ ]:
for i in data.columns:
    sns.FacetGrid(data['target'],size=8)\
        .map(sns.distplot ,i)
plt.legend()    


In [ ]:
rf = RandomForestClassifier( max_depth=10, verbose=3, n_estimators=20)
parameters = {'n_estimators': [120, 100], 'max_depth':[3,5,]}
grid = GridSearchCV(rf, parameters, cv=3, n_jobs=-1, verbose=3, scoring=make_scorer(roc_auc_score))

In [ ]:
df_train_FS=data
grid.fit(df_train_FS.drop(["target",'ID_code'], axis=1).values, df_train_FS.target.values)


In [ ]:
grid.best_score_


In [ ]:
from sklearn import tree


In [ ]:
#linear regression
X=data.drop(columns=['ID_code','target'],axis=1)
test=data.drop(columns=['ID_code'],axis=1)
y=data['target']
X_train,X_valid,y_train,y_valid=train_test_split(X,y,random_state=42)
lr = LinearRegression()
lr.fit(X_train,y_train)
#print(lr.intercept_)
#print(lr.coef_)
y_pred = lr.predict(X_valid)
y_pred

print('Shape of X_train :',X_train.shape)
print('Shape of X_valid :',X_valid.shape)
print('Shape of y_train :',y_train.shape)
print('Shape of y_valid :',y_valid.shape)

In [ ]:
y_valid = np.array(list(y_valid))
y_pred = np.array(y_pred)




In [ ]:
df = pd.DataFrame({'Actual': y_valid.flatten(), 'Predicted': y_pred.flatten()})
df


In [ ]:
plt.scatter(X_valid, y_valid,  color='gray')
plt.plot(X_valid, y_pred, color='red', linewidth=2)
plt.show()


In [ ]:
# mail
%%time
#Random forest classifier
rf_model=RandomForestClassifier(n_estimators=10,random_state=42)
#fitting the model
rf_model.fit(X_train,y_train) 

In [ ]:
#
%%time
#Permutation importance
from eli5.sklearn import PermutationImportance
perm_imp=PermutationImportance(rf_model,random_state=42)
#fitting the model
perm_imp.fit(X_valid,y_valid)

In [ ]:
#decision trees
feature_cols = data.drop(["target",'ID_code'], axis=1)
X = data[feature_cols]
y = data.label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


In [ ]:
#logistic regression
feature_cols1 = data.drop(["target",'ID_code'], axis=1)
X = data[feature_cols1]
y = data.label

In [ ]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X_train,y_train)

#
y_pred=logreg.predict(X_test)